### ISSUE TITLE
git checkout warning: case-insensitive paths collided

### ISSUE THREAD

**Issue by manuel3108** [open-source-labs/SvelteStorm#56]
Checkout the repo on windows, and you will get something like the following output. But its just a warning, so its probably fine for the moment

![image](https://user-images.githubusercontent.com/30698007/126289636-dea7ac13-e036-45c4-9ab3-3465f15ea100.png)

**Comment by NesTar6** [comment]
Hi, closing this issue after pull request #59. Thank you @ayemmoe !
